const normalized=v=>v.trim().toLowerCase().replace(/\s+/g,' ');
const emptyAnswers=new Set(['no','none','nil','na','n/a','nothing','not applicable','idk','unknown','-']);
const hasLongRepeat=v=>/(.)\1{3,}/i.test(v.replace(/\s/g,''));
const isMeaningful=v=>v.trim().length>=3&&!emptyAnswers.has(normalized(v))&&!hasLongRepeat(v);
const educationPattern=/\b(b\.?tech|b\.?e\.?|bsc|b\.sc|bca|bba|ba|b\.a|bcom|b\.com|m\.?tech|m\.?e\.?|msc|m\.sc|mca|mba|ma|m\.a|mcom|m\.com|bachelor|master|diploma|degree|engineering|college|university|12th|class 12|computer science|commerce|arts|science)\b/i;

const fields=[
  {key:'internshipArea',ask:'First, which <strong>internship area</strong> are you applying for?',placeholder:'Choose or type an internship area',validate:isMeaningful,error:'Please choose a genuine internship area, such as Software Development, Finance, Marketing, or Design.',options:['Software Development','Data Science','Digital Marketing','Human Resources','Finance','UI/UX Design']},
  {key:'name',ask:'Let\'s begin with your <strong>full name</strong>.',placeholder:'e.g. Priya Sharma',validate:v=>{const words=v.trim().split(/\s+/);return words.length>=2&&words.every(w=>/^[a-zA-Z][a-zA-Z.'-]{1,}$/.test(w))&&!hasLongRepeat(v)},error:'Please enter your real full name with at least a first and last name.'},
  {key:'email',ask:'Nice to meet you! What is your <strong>email address</strong>?',placeholder:'you@example.com',validate:v=>{const value=v.trim();const local=value.split('@')[0]||'';return /^[^\s@]+@[^\s@]+\.[a-zA-Z]{2,}$/.test(value)&&!hasLongRepeat(local)&&!/(test|fake|example){2,}/i.test(local)},error:'Please enter a valid personal email address without placeholder or repeated text.'},
  {key:'degree',ask:'What <strong>degree or course</strong> are you currently pursuing?',placeholder:'e.g. B.Tech Computer Science',validate:v=>isMeaningful(v)&&educationPattern.test(v)&&!/kindergarten|nursery|primary school/i.test(v),error:'Please enter a recognized current degree, diploma, or higher-secondary course.'},
  {key:'specialization',ask:'Is there a particular <strong>role or specialization</strong> you are interested in?',placeholder:'e.g. Frontend development, recruitment, branding',validate:v=>(normalized(v)==='open to options'||isMeaningful(v))&&!/^(ceo|owner|boss|president)$/i.test(v.trim()),error:'Please enter an internship-level role or specialization, or choose “Open to options”.',options:['Open to options']},
  {key:'skills',ask:'Which <strong>skills or tools</strong> have you used? A beginner answer is completely fine.',placeholder:'e.g. Python, Excel, SQL',validate:v=>normalized(v)==='beginner'||isMeaningful(v),error:'Add at least one genuine skill or tool, or choose “Beginner”.',options:['Python & SQL','Excel & Power BI','Beginner']},
  {key:'experience',ask:'Last one: briefly share any <strong>project or relevant experience</strong>.',placeholder:'A course project or “No experience yet”',validate:v=>['no experience yet','coursework only'].includes(normalized(v))||(isMeaningful(v)&&v.trim().length>=10),error:'Please briefly describe an experience, or choose “No experience yet” or “Coursework only”.',options:['No experience yet','Coursework only']}
];
const state={step:0,data:{}};const messages=document.querySelector('#messages');const input=document.querySelector('#messageInput');const suggestions=document.querySelector('#suggestions');const form=document.querySelector('#chatForm');
function addMessage(html,who='bot',error=false){const row=document.createElement('div');row.className=`message ${who}`;if(who==='bot')row.innerHTML='<div class="mini-avatar">RA</div>';const bubble=document.createElement('div');bubble.className=`bubble${error?' error':''}`;bubble.innerHTML=html;row.appendChild(bubble);messages.appendChild(row);messages.scrollTop=messages.scrollHeight}
function setSuggestions(items=[]){suggestions.innerHTML='';items.forEach(label=>{const b=document.createElement('button');b.type='button';b.className='chip';b.textContent=label;suggestions.appendChild(b)})}
function updateProgress(){const pct=Math.min(100,8+state.step*13);document.querySelector('#progressBar').style.width=`${pct}%`;const ranges=[[0,1],[1,3],[3,7],[7,8]];document.querySelectorAll('.steps li').forEach((li,i)=>{const [start,end]=ranges[i];li.classList.toggle('active',state.step>=start&&state.step<end);li.classList.toggle('done',state.step>=end)})}
function ask(){if(state.step<fields.length){const f=fields[state.step];setTimeout(()=>{addMessage(f.ask);input.placeholder=f.placeholder;setSuggestions(f.options);input.focus()},280)}else review()}
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function submitText(raw){const value=raw.trim();if(!value)return;if(/^(faq|help|question)/i.test(value)){addMessage(escapeHtml(value),'user');addMessage('I can help. Tap <strong>FAQs</strong> above, or continue your application by answering the current question.');return}addMessage(escapeHtml(value),'user');setSuggestions([]);const f=fields[state.step];if(!f.validate(value)){setTimeout(()=>{addMessage(f.error,'bot',true);setSuggestions(f.options);input.focus()},220);return}state.data[f.key]=value;state.step++;updateProgress();ask()}
function review(){input.placeholder='Type confirm, edit, or cancel';const d=state.data;addMessage(`<strong>Everything looks ready.</strong> Please check your details.<div class="summary"><div><small>Internship area</small><b>${escapeHtml(d.internshipArea)}</b></div><div><small>Name</small><b>${escapeHtml(d.name)}</b></div><div><small>Email</small><b>${escapeHtml(d.email)}</b></div><div><small>Degree</small><b>${escapeHtml(d.degree)}</b></div><div><small>Specialization</small><b>${escapeHtml(d.specialization)}</b></div><div><small>Skills</small><b>${escapeHtml(d.skills)}</b></div><div><small>Experience</small><b>${escapeHtml(d.experience)}</b></div></div>`);setSuggestions(['Confirm & submit','Edit details','Cancel'])}
function complete(){const id=`INT-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;const record={registrationId:id,submittedAt:new Date().toISOString(),program:`${state.data.internshipArea} Internship`,...state.data};localStorage.setItem('internly_registration',JSON.stringify(record));addMessage(`<div class="success-card"><div class="success-icon">✓</div><strong>Registration complete!</strong><p>Your application ID is</p><div class="registration-id">${id}</div><p>Keep this ID for your records.</p><button class="download" id="downloadBtn">Download summary</button></div>`);setSuggestions(['Start another registration']);input.disabled=true;document.querySelector('#downloadBtn').onclick=()=>download(record);document.querySelector('.send-button').disabled=true;state.step=8;updateProgress()}
function download(record){const blob=new Blob([JSON.stringify(record,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${record.registrationId}.json`;a.click();URL.revokeObjectURL(a.href)}
function reset(){state.step=0;state.data={};messages.innerHTML='';input.disabled=false;document.querySelector('.send-button').disabled=false;input.value='';updateProgress();addMessage('<strong>Hello! I\'m your internship registration assistant.</strong><br>I\'ll help you register for the internship area that fits you. It takes about two minutes.');setSuggestions(['Start registration','View FAQs']);input.placeholder='Say hello or tap Start registration'}
function handleCommand(value){if(state.step===0&&!state.data.internshipArea&&/^(start|hello|hi|hey)/i.test(value)){addMessage(escapeHtml(value),'user');setSuggestions([]);ask();return true}if(state.step>=fields.length){addMessage(escapeHtml(value),'user');if(/confirm|submit|yes/i.test(value)){setSuggestions([]);setTimeout(complete,300)}else if(/edit/i.test(value)){state.step=0;state.data={};addMessage('No problem. We\'ll go through the details again.');updateProgress();ask()}else if(/cancel/i.test(value)){addMessage('Your application was cancelled. No details were submitted.');setSuggestions(['Start over'])}else addMessage('Please choose <strong>Confirm &amp; submit</strong>, <strong>Edit details</strong>, or <strong>Cancel</strong>.','bot',true);return true}return false}
form.addEventListener('submit',e=>{e.preventDefault();const v=input.value.trim();input.value='';if(!v)return;if(!handleCommand(v))submitText(v)});suggestions.addEventListener('click',e=>{if(!e.target.matches('.chip'))return;const v=e.target.textContent;if(v==='View FAQs')document.querySelector('#faqDialog').showModal();else if(v==='Start registration'){addMessage(v,'user');setSuggestions([]);ask()}else if(v==='Confirm & submit'){addMessage(v,'user');setSuggestions([]);setTimeout(complete,300)}else if(v==='Edit details'){addMessage(v,'user');state.step=0;state.data={};updateProgress();setSuggestions([]);setTimeout(()=>{addMessage('No problem. Let\'s update your information.');ask()},220)}else if(v==='Cancel'){addMessage(v,'user');setSuggestions(['Start over']);addMessage('Your application was cancelled. No details were submitted.')}else if(v==='Start over'||v==='Start another registration')reset();else submitText(v)});document.querySelector('#faqButton').onclick=()=>document.querySelector('#faqDialog').showModal();document.querySelector('#closeFaq').onclick=()=>document.querySelector('#faqDialog').close();document.querySelector('#restartTop').onclick=reset;reset();
